# Generated by Django 6.0.2 on 2026-03-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='not provided', max_length=500),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='not provided', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(default='nursery', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='not provided', max_length=14),
        ),
    ]
